<?php return array (
  'web_name' => 'Bettpro',
  'color_code' => 'fff',
  'contact_address' => 'Berlin,Germany',
  'contact_email' => 'support@example.com',
  'contact_phone' => '0123654789',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'paginate' => 15,
  'copyright_text' => 'All Rights Reserved',
  'sender_email' => NULL,
  'sender_email_name' => NULL,
  'email_description' => 'Hi {{name}}, {{message}} , Thank you',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => NULL,
    'smtp_port' => '587',
    'smtp_encryption' => 'tls',
    'smtp_username' => NULL,
    'smtp_password' => NULL,
  ),
  'global_email' => 'support@mail.com',
  'global_description' => 'Hi {{name}}, {{message}} , Thank you',
);